#!/bin/sh

. /lib/functions.sh
board=$(board_name)

if [ $board != "mxl,lgm" && [ "$board" != "mxl,osp-tb341" ] && [ "$board" != "mxl,osp-tb341-v2" ]; then
    exit 0
fi

/etc/init.d/netdev_cfg.sh disable
/etc/init.d/mxl-network-init disable

exit 0

